### PR TITLE
Addition of configuration handling + a couple of targets

### PR DESCRIPTION
**Pull request by Jekotia**
I should note that I am new to Make. I wouldn't be surprised if there's best-practices violations. If there are, let me know and I'll fix them before re-submitting.

### Major additions

In order to make this already fantastic Makefile more versatile, I added configuration handling. This allows the Makefile itself to be entirely independent of a users configuration. and more easily update the Makefile on the user end if changes to the Makefile are published. All examples have been updated to reflect this change.

### Minor additions

I also added two new targets, help & latest. As per my README changes:
* Added 'help' target, to list available targets along with a brief description.
* Added 'latest' target, for edge-cases where tagging the resulting image as latest, without version, is preferred.

### Other various changes

I also decided to tidy the repo a little, as I don't feel files such as .release should be part of the repository under the examples; these files, while essential to run time, are created by the Makefile at runtime.

### CODE REVIEW

**Comment by ghost** [comment]
It would be nice if those changes were indeed merged.

**Comment by Jekotia** [comment]
@mvanholsteijn Any thoughts on this?

**Comment by ghost** [comment]
@Jekotia I used your PR and it is working really well for me.

**Comment by dmumber** [comment]
what @ygworldr  says goes for me too.

**Comment by mvanholsteijn** [comment]
@Jekotia thank you for your suggestion. I am sorry to say that I am not going to merge the config.mk setup into the main branch.

When I want to make a configuration change, I just add them to the Makefile of the source file.

For instance in multiple-example/image1 I would add:

```
include ../make/Makefile

USERNAME=binxio
```

Or:

```
include ../make/Makefile
include ../make/config.mk
```


This would allow you to override any of the defaults, without moving the complexity of the configuration into the generic makefile.

**Pull request closed without merging**
